# Generated by Django 3.2.15 on 2022-11-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_email', models.EmailField(default='dan.tymoshenko228@gmail.com', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
