# Generated by Django 3.2.15 on 2022-12-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In money'), (1, 'In percent')], default=0),
        ),
    ]
